### ISSUE TITLE
Release version.

### ISSUE THREAD

**Issue by SolitudeSF** [tropf/tmines#1]
I want to add your game to [Void Linux packages](https://github.com/voidlinux/void-packages), but non-release versions of packages [cant be accepted](https://github.com/voidlinux/void-packages/blob/master/CONTRIBUTING.md#getting-your-packages-into-void-by-yourself) to the repo.
This program seems fully functional so im sure bumping it to release version wouldnt be a problem.

**Comment by tropf** [comment]
Well said, commit has been tagged.

**Comment by SolitudeSF** [comment]
Appreciated
